### ISSUE TITLE
Issue with listing choices

### ISSUE THREAD

**Issue by MJStokes86** [MJStokes86/Project-4-Name_That_Tube#2]
I have been trying to come up with a database call that would give me everything from the choices column from the questionnaires table. I was able to iterate and list the choices themselves but they have their own index value

The code @choices = Questionnaire.select(:choices).all[0]   gives me just the first one

I want the database call to be @choices = Questionnaire.select(:choices).all[i] that would allow me to access all of them regardless. I have tried loops that I can think of. If you are still available please help me out. I have struggled all day on this. Thanks!

Michael

**Comment by jkonowitch** [comment]
`@choices = Questionnaire.all` should return an array of all questionnaires. Have you tried that?

**Comment by MJStokes86** [comment]
It returns 

 #<Questionnaire:0x007f75685832b8>
 #<Questionnaire:0x007f7568583060>
 #<Questionnaire:0x007f7568582e08>
 #<Questionnaire:0x007f7568582bb0>

**Comment by MJStokes86** [comment]
When I do @choices = Questionnaire.select(:choices).map{|c| c.choices}[0] it returns what I want but only from the first one.

**Comment by MJStokes86** [comment]
My questionnaire table has a 'choices' column with has an array. Inside the array are the multiple choices. I was able to spit out everything from the array into radio buttons. When I go to another category to answer another question, I still get the multiple choice from the first question and I don't want that. I want my multiple choices to match my categories.

**Comment by jkonowitch** [comment]
> #Questionnaire:0x007f75685832b8
> #Questionnaire:0x007f7568583060
> #Questionnaire:0x007f7568582e08
> #Questionnaire:0x007f7568582bb0

Those are questionnaire objects. Try calling `.choices` on them

**Comment by MJStokes86** [comment]
Dosen't work!

q.select('choices').choices

  Questionnaire Load (1.5ms)  SELECT "questionnaires"."choices" FROM "questionnaires"
NoMethodError: undefined method `choices' for #<Questionnaire::ActiveRecord_Relation:0x007f18a26fd120>
from /home/michael/.rbenv/versions/2.0.0-dev/lib/ruby/gems/2.0.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:136:in `method_missing'

**Comment by MJStokes86** [comment]
I have to put an index value at the end to get what I want. I want a global index value like [i] to get them all. 



 q.select('choices').all[0].choices

  Questionnaire Load (5.8ms)  SELECT "questionnaires"."choices" FROM "questionnaires"
=> ["1982 Michael Jackson Bille Jean",
 "1984 Madonna Like a virgin",
 "1981 The Buggles Video Killed The Radio Star"]

**Comment by MJStokes86** [comment]
When I do Questionnaire.select(:choices).map{|c| c.choices}, I get a nested array with all my choices. 

  Questionnaire Load (1.5ms)  SELECT "questionnaires"."choices" FROM "questionnaires"
=> [["1982 Michael Jackson Bille Jean",
  "1984 Madonna Like a virgin",
  "1981 The Buggles Video Killed The Radio Star"],
 ["Designing Women", "The Facts of Life", "Girlfriends"],
 ["The Last Dragon", "The Karate Kid", "Big Trouble in Little China"],
 ["Battletoads", "Sonic The Hedgehog", "Jewel Master"]]

I want to get inside the parent array so all my choices can be listed as:

["1982 Michael Jackson Bille Jean",
  "1984 Madonna Like a virgin",
  "1981 The Buggles Video Killed The Radio Star"],

 ["Designing Women", "The Facts of Life", "Girlfriends"],

 ["The Last Dragon", "The Karate Kid", "Big Trouble in Little China"],

 ["Battletoads", "Sonic The Hedgehog", "Jewel Master"]

**Comment by jkonowitch** [comment]
```ruby
questions = Questionnaire.all
questions.each do |q|
  puts q.choices
end
```

**Comment by MJStokes86** [comment]
#<Questionnaire:0x007fe64432e538>
 #<Questionnaire:0x007fe64432e290>
 #<Questionnaire:0x007fe64432dfe8>
 #<Questionnaire:0x007fe64432dd68>

They way I want my code to work is for each element in ['a', 'b', 'c'] would spit out in radio buttons as:
a
b
c

I have it working for only the first question, but I would like my choices to be connected to their own question. You have to see my work in person so you can understand exactly the way I want my code to work.

**Comment by MJStokes86** [comment]
![image](https://cloud.githubusercontent.com/assets/11261672/8039363/29187bd6-0dd7-11e5-9222-376e40d5a3fb.png)
